version : '1' # Version of Docker Compose Format

services:
  driver-service:
    restart: always
    build: ./service/driver
    volumes:
      - /user/src/app/static
    expose:
      - "8000"
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - driver-service
    links:
      - haproxy
      - driver-service: driver-service
  haproxy:
    image: 'dockercloud/haproxy:latest'
    links:
        - driver-service
    environment:
        - BACKEND_PORT=8000